using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using System.Web.UI;
using DevExpress.Web;

[assembly: AllowPartiallyTrustedCallers]
[assembly: AssemblyTitle("")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]
[assembly: ThemesAssembly]

[assembly: ComVisible(false)]

[assembly: Guid("f5eccea9-008d-48d4-ba73-cd0bbfa1af0a")]

[assembly: AssemblyVersion(AssemblyInfo.Version)]
[assembly: AssemblyFileVersion(AssemblyInfo.FileVersion)]

[assembly: AssemblyKeyName("")]

[assembly: WebResourceAssembly(101)]

[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxButton.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxButtonEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxCalendar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxCallbackPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxCaptcha.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxChartControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxCheckBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxCheckBoxList.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxCloudControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxColorEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxComboBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxDataView.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxDateEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxDateNavigator.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxDockPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxDropDownEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxFileManager.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxFilterControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxGridLookup.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxGridView.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxHeadline.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxHtmlEditor.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxHyperLink.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxLabel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxListBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxLoadingPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxMemo.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxMenu.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxNavBar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxNewsControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxPageControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxPager.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxPivotGrid.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxPopupControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxPopupMenu.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxProgressBar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxRadioButton.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxRadioButtonList.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxRatingControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxRoundPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxScheduler.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxSiteMapControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxSpellChecker.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxSpinEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxSplitter.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTabControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTextBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTimeEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTitleIndex.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTrackBar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTreeList.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxTreeView.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxUploadControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ASPxValidationSummary.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MonthEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxButton.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxButtonEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxCalendar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxCaptcha.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxCallbackPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxChartControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxCheckBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxCheckBoxList.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxColorEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxComboBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxDataView.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxDateEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxDockPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxDropDownEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxFileManager.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxGridView.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxHtmlEditor.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxHyperLink.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxLabel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxListBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxLoadingPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxMemo.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxMenu.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxNavBar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxPageControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxPivotGrid.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxPopupControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxPopupMenu.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxProgressBar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxRadioButton.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxRadioButtonList.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxReportToolbar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxReportViewer.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxRoundPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxScheduler.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxSpinEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxSplitter.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxTabControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxTextBox.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxTimeEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxTrackBar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxTreeView.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxUploadControl.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.MVCxValidationSummary.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.RecurrenceTypeEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ReportDocumentMap.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ReportParametersPanel.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ReportToolbar.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.ReportViewer.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.WeekDaysEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.WeekOfMonthEdit.skin", "text")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Chart.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Chart.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.BtnBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.caChallengeImageBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.DarkGrey.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.DarkPink.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtBtnBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtBtnDisabledBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtBtnHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtBtnPBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtDropDownBtnHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtDropDownBtnPBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtProgressBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtProgressIndicatorBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarBarHighlightH.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarBarHighlightV.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarDoubleLargeTickH.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarDoubleLargeTickV.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarDoubleSmallTickH.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarDoubleSmallTickV.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarLargeTickH.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarLargeTickV.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarSmallTickH.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarSmallTickV.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackGrey.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackH.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackLeft.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackRight.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackScale.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackTurquoise.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.edtTrackBarTrackV.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.Grey.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.lbHeaderBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.LogonTextBoxBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.TextBoxBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.Turquoise.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Editors.Yellow.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.GridHSeparator.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.GridVSeparator.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.gvFocusedBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.gvGroupPanelBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.gvHeaderBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.gvPagerPanelBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.gvTitleBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.StatusBarLoading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.GridView.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.Bar-Line.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.SBTabBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.SBTabHoverBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.ToolbarBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.HtmlEditor.ToolbarBackRtl.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.FLsprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.FLsprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.HeaderBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.HeaderHoverBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.PagerBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.pcHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.TitleBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.PivotGrid.tvNodeLoading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.CssImages.ToolbarBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.CssImages.ViewSelectorButtonBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.CssImages.ViewSelectorButtonHoverBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Scheduler.CssImages.ViewSelectorButtonPressedBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.SpellChecker.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.SpellChecker.scErrorUnderline.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.SpellChecker.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.AltBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.ControlBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.FocusedBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.HeaderBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.PagerBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.PreviewBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.TreeList.CssImages.TitleBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.Active.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.dvItemBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.dvPagerPanelBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.dvPagerPanelSpacingBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.edtBtnBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.edtBtnDisabledBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.edtBtnHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.fmSplitterSeparator.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.Hover_23.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.Inactive.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.Loading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mHorzItemSepBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mItemBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mItemHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mItemHover.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mItemSBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mScrollHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mScrollPBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mSubItemHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mSubItemSepBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.mVertItemSepBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.nbHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.nbIHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.nbISBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ncPagerPanelSpacingBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.pcFBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.pcHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.pDropDownButtonHoverBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.pDropDownButtonPressedBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.PopupBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.pSepBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.rcMapImage.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.rpHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.rpTEdgeBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ScrollBtn.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.Selected_23.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.Separator.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.splHSepHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.splResizingPointer.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.splVSepHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.sprite.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.styles.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.tcTabBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.tcTabHoverBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.TextBoxBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.tiFBBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.tiHBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ToolbarBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.tvNodeLoading.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.UcBbBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ucButtonBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ucButtonDisabledBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ucButtonHoverBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ucButtonPressedBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ucProgressBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.ucProgressIndicatorBack.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.Web.VisitTabsWrapperBkg.png", "image/png")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.XtraReports.sprite.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.XtraReports.sprite.gif", "image/gif")]
[assembly: WebResource("ClinicalStudyThemeAssembly.App_Themes.ClinicalStudyTheme.XtraReports.sprite.png", "image/png")]

